name: Algolia - Documentation
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oceanroleplay/action-algolia-docsearch@master
        with:
          algolia_application_id: ${{ secrets.ALGOLIA_API_KEY }}
          algolia_api_key: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          config_file: "docs/config.json"
