name: Algolia - Documentation
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: ${{ secrets.ALGOLIA_API_KEY }}
          algolia_api_key: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          file: "docs/config.json"
