name: Build - Stable
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Update version
        run: npm version 6.0.6

      - name: Install root dependencies
        run: npm ci

      - name: Install latest discord.js
        run: npm install discord.js@latest

      - name: Publish branch
        run: |
          git config user.email ${{ secrets.GIT_EMAIL }}
          git config user.name ${{ secrets.GIT_NAME }}
          git add -A
          git commit -m release
          git push --force origin main:stable
