name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    paths-ignore:
      - "docs/docs/**"
    branches:
      - main

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Run prettier
        run: npm run format-check

  jest:
    name: Jest Tests
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install
        working-directory: ./packages/discordx

      - name: Build
        run: npm run build
        working-directory: ./packages/discordx

      - name: Run Tests
        run: npm run test
        working-directory: ./packages/discordx

  build:
    name: Build discordx
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install
        working-directory: ./packages/discordx

      - name: Build
        run: npm run type-check
        working-directory: ./packages/discordx

  build-changelog:
    name: Build @discordx/changelog
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: "Install dependencies"
        run: npm install
        working-directory: ./packages/changelog

      - name: "Build"
        run: npm run type-check
        working-directory: ./packages/changelog

  build-di:
    name: Build @discordx/di
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install
        working-directory: ./packages/di

      - name: Build
        run: npm run type-check
        working-directory: ./packages/di

  build-importer:
    name: Build @discordx/importer
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: "Install dependencies"
        run: npm install
        working-directory: ./packages/importer

      - name: "Build"
        run: npm run type-check
        working-directory: ./packages/importer

  build-internal:
    name: Build @discordx/internal
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: "Install dependencies"
        run: npm install
        working-directory: ./packages/internal

      - name: "Build"
        run: npm run type-check
        working-directory: ./packages/internal

  build-koa:
    name: Build @discordx/koa
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: "Install dependencies"
        run: npm install
        working-directory: ./packages/koa

      - name: "Build"
        run: npm run type-check
        working-directory: ./packages/koa

  build-music:
    name: Build @discordx/music
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: "Install dependencies"
        run: npm install
        working-directory: ./packages/music

      - name: "Build"
        run: npm run type-check
        working-directory: ./packages/music

  build-utilities:
    name: Build @discordx/utilities
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: "Install dependencies"
        run: npm install
        working-directory: ./packages/utilities

      - name: "Build"
        run: npm run type-check
        working-directory: ./packages/utilities

  build-pagination:
    name: Build @discordx/pagination
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: "Install dependencies"
        run: npm install
        working-directory: ./packages/pagination

      - name: "Build"
        run: npm run type-check
        working-directory: ./packages/pagination
