name: Build - Stable
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Initialize gif config
        run: |
          git config user.email ${{ secrets.GIT_EMAIL }}
          git config user.name ${{ secrets.GIT_NAME }}

      - name: Synchronize current version
        run: npm version --git-tag-version=false $(npm view discordx version)

      - name: Update version
        run: npm version --git-tag-version=false patch

      - name: Install root dependencies
        run: npm ci

      - name: Install latest discord.js
        run: npm install discord.js@latest

      - name: Publish branch
        run: |
          git add -A
          git commit -m release $(jq --raw-output '.version' package.json)
          git push --force origin main:stable
