name: Deprecate - NPM Version
on:
  workflow_dispatch:
    inputs:
      version:
        description: "npm version range"
        required: true
        type: string
      message:
        description: "deprecate message"
        default: "no longer supported, update to latest version"
        required: false
        type: string
      version:
        description: "package"
        default: "discordx"
        required: false
        type: string

jobs:
  deprecate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Deprecate version
        run: npm deprecate discordx@"${{ github.event.inputs.version }}" "${{ github.event.inputs.message }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
