name: Deprecate - NPM Version
on:
  workflow_dispatch:
      package:
        description: "package"
        required: true
        type: string
    inputs:
      version:
        description: "npm version range"
        required: true
        type: string
      message:
        description: "deprecate message"
        default: "no longer supported, update to latest version"
        required: true
        type: string

jobs:
  deprecate:
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Deprecate version
        run: npm deprecate ${{ github.event.inputs.package }}@"${{ github.event.inputs.version }}" "${{ github.event.inputs.message }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
