name: Publish - Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/docs/**"
      - "docs/i18n/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install root dependencies
        run: npm ci

      - name: Install doc dependencies
        run: npm ci
        working-directory: ./docs

      - name: Build docs
        run: npm run build
        working-directory: ./docs

      - name: Publish git branch
        run: |
          git init -b docs
          git config user.email ${{ secrets.GIT_EMAIL }}
          git config user.name ${{ secrets.GIT_NAME }}
          git add -A
          git commit -m 'docs'
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push --force --set-upstream origin docs
        working-directory: ./docs/build
