name: Publish - Utilities
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install root dependencies
        run: npm ci

      - name: Install utilities dependencies
        run: npm ci
        working-directory: ./packages/utilities

      - name: Build
        run: npm run build
        working-directory: ./packages/utilities

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/utilities
