name: Publish - Documentation
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install root dependencies
        run: npm ci

      - name: Install doc dependencies
        run: npm ci
        working-directory: ./docs

      - name: Build docs
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
        working-directory: ./docs

      - name: Get main branch hash
        id: getMainHash
        run: echo '::set-output name=hash::${git rev-parse HEAD}';

      - name: Check out gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs/document

      - name: Push Doc
        run: |
          cp -r ../build/* ./
          git config user.email ${{ secrets.GIT_EMAIL }}
          git config user.name ${{ secrets.GIT_NAME }}
          git add -A
          git commit -m "${{ steps.getMainHash.outputs.hash }}"
          git push origin gh-pages
        working-directory: ./docs/document
