name: Publish - Dev
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: pre-release
        id: pre-release
        run: |
          if [[ $(npm view discordx@dev version | grep -e "$(jq --raw-output '.version' package.json).*.$(git rev-parse --short HEAD | cut -b1-7)") ]]; \
          then echo '::set-output name=release::false'; \
          else echo '::set-output name=release::true'; fi

      - name: Install dependencies
        if: steps.pre-release.outputs.release == 'true'
        run: npm ci --ignore-scripts

      - name: Build
        if: steps.pre-release.outputs.release == 'true'
        run: npm run build

      - name: Deprecate old versions
        if: steps.pre-release.outputs.release == 'true'
        run: npm deprecate discordx@"~$(jq --raw-output '.version' package.json)" "no longer supported" || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: steps.pre-release.outputs.release == 'true'
        run: |
          npm version --git-tag-version=false $(jq --raw-output '.version' package.json).$(date +%s).$(git rev-parse --short HEAD)
          npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
