name: Publish - Dev
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  publish:
    name: Publish Main
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Synchronize dev version
        run: |
          npm version --git-tag-version=false $(npm view discordx version)
          npm version --git-tag-version=false major
          npm version --git-tag-version=false "$(jq --raw-output '.version' package.json)-dev"

      - name: Update version
        run: npm version --git-tag-version=false ${{ github.event.inputs.version }}

      - name: pre-release
        id: pre-release
        run: |
          if [[ $(npm view discordx@dev version | grep -e "$(jq --raw-output '.version' package.json).*.$(git rev-parse --short HEAD | cut -b1-3)") ]]; \
          then echo '::set-output name=release::false'; \
          else echo '::set-output name=release::true'; fi

      - name: Install Dependencies
        if: steps.pre-release.outputs.release == 'true'
        run: npm install

      - name: Build
        if: steps.pre-release.outputs.release == 'true'
        run: npm run build

      - name: Deprecate old versions
        if: steps.pre-release.outputs.release == 'true'
        run: npx @favware/npm-deprecate -d --name "*dev*" --package "discordx" --message "Version no longer supported. Upgrade to @latest"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: steps.pre-release.outputs.release == 'true'
        run: |
          npm version --git-tag-version=false $(jq --raw-output '.version' package.json).$(date +%s).$(git rev-parse --short HEAD)
          npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
