name: Publish - Documentation
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install root dependencies
        run: npm ci

      - name: Install doc dependencies
        run: npm ci
        working-directory: ./docs

      - name: Build docs
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
        working-directory: ./docs

      - name: Add CNAME
        run: echo discord-ts.js.org > CNAME
        working-directory: ./docs/build

      - name: check out gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs/document

      - name: Push update
        run: |
          cp -r ../build/* ./
          git config user.email ${{ secrets.GIT_EMAIL }}
          git config user.name ${{ secrets.GIT_NAME }}
          git add -A
          git commit -m '$(date +%s).$(git rev-parse --short HEAD)'
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push
        working-directory: ./docs/document
