name: Publish - Stable
on:
  workflow_dispatch:
    inputs:
      package:
        description: "package name"
        required: true
        type: string
      version:
        description: "npm version"
        default: "patch"
        required: true
        type: string

jobs:
  build:
    name: Build discordx
    runs-on: ubuntu-latest
    if: github.event.inputs.package == 'discordx'
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Synchronize current version
        run: npm version --git-tag-version=false $(npm view discordx version)
        working-directory: ./packages/discordx

      - name: Update version
        run: npm version --git-tag-version=false ${{ github.event.inputs.version }}
        working-directory: ./packages/discordx

      - name: Install root dependencies
        run: npm install
        working-directory: ./packages/discordx

      - name: Install latest discord.js
        run: npm install discord.js@latest
        working-directory: ./packages/discordx

      - name: Build
        run: npm run build
        working-directory: ./packages/discordx

      - name: Publish
        run: npm publish
        working-directory: ./packages/discordx
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-changelog:
    name: Build @discordx/changelog
    runs-on: ubuntu-latest
    if: github.event.inputs.package == '@discordx/changelog'
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Synchronize current version
        run: npm version --git-tag-version=false $(npm view @discordx/changelog version)
        working-directory: ./packages/changelog

      - name: Update version
        run: npm version --git-tag-version=false ${{ github.event.inputs.version }}
        working-directory: ./packages/changelog

      - name: Install changelog dependencies
        run: npm install
        working-directory: ./packages/changelog

      - name: Build
        run: npm run build
        working-directory: ./packages/changelog

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/changelog

  build-importer:
    name: Build @discordx/importer
    runs-on: ubuntu-latest
    if: github.event.inputs.package == '@discordx/importer'
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Synchronize current version
        run: npm version --git-tag-version=false $(npm view @discordx/importer version)
        working-directory: ./packages/importer

      - name: Update version
        run: npm version --git-tag-version=false ${{ github.event.inputs.version }}
        working-directory: ./packages/importer

      - name: Install importer dependencies
        run: npm install
        working-directory: ./packages/importer

      - name: Build
        run: npm run build
        working-directory: ./packages/importer

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/importer

  build-music:
    name: Build @discordx/music
    runs-on: ubuntu-latest
    if: github.event.inputs.package == '@discordx/music'
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Synchronize current version
        run: npm version --git-tag-version=false $(npm view @discordx/music version)
        working-directory: ./packages/music

      - name: Update version
        run: npm version --git-tag-version=false ${{ github.event.inputs.version }}
        working-directory: ./packages/music

      - name: Install music dependencies
        run: npm install
        working-directory: ./packages/music

      - name: Install latest discord.js
        run: |
          npm install discord.js@latest
          npm install -D discordx@latest
        working-directory: ./packages/music

      - name: Build
        run: npm run build
        working-directory: ./packages/music

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/music

  build-utilities:
    name: Build @discordx/utilities
    runs-on: ubuntu-latest
    if: github.event.inputs.package == '@discordx/utilities'
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Synchronize current version
        run: npm version --git-tag-version=false $(npm view @discordx/utilities version)
        working-directory: ./packages/utilities

      - name: Update version
        run: npm version --git-tag-version=false ${{ github.event.inputs.version }}
        working-directory: ./packages/utilities

      - name: Install utilities dependencies
        run: npm install
        working-directory: ./packages/utilities

      - name: Install latest discord.js
        run: |
          npm install discord.js@latest
          npm install -D discordx@latest
        working-directory: ./packages/utilities

      - name: Build
        run: npm run build
        working-directory: ./packages/utilities

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/utilities

  build-pagination:
    name: Build @discordx/pagination
    runs-on: ubuntu-latest
    if: github.event.inputs.package == '@discordx/pagination'
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Synchronize current version
        run: npm version --git-tag-version=false $(npm view @discordx/pagination version)
        working-directory: ./packages/pagination

      - name: Update version
        run: npm version --git-tag-version=false ${{ github.event.inputs.version }}
        working-directory: ./packages/pagination

      - name: Install pagination dependencies
        run: npm install
        working-directory: ./packages/pagination

      - name: Install latest discord.js
        run: |
          npm install discord.js@latest
          npm install -D discordx@latest
        working-directory: ./packages/pagination

      - name: Build
        run: npm run build
        working-directory: ./packages/pagination

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/pagination
