name: Test - Type
on:
  # workflow_dispatch:
  pull_request:
    paths-ignore:
      - "docs/docs/**"
    branches:
      - main
      - stable
  push:
    paths-ignore:
      - "docs/docs/**"
    branches:
      - main
      - stable

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript compiler
        run: npm run type-check
