name: Test - Documentation
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "docs/docs/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install root dependencies
        run: npm ci

      - name: Install doc dependencies
        run: npm ci
        working-directory: ./docs

      - name: "Utilities: Install Dependencies"
        run: npm ci
        working-directory: ./packages/utilities

      - name: "Music: Install Dependencies"
        run: npm ci
        working-directory: ./packages/music

      - name: Build docs
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
        working-directory: ./docs

      - name: Add CNAME
        run: echo discord-ts.js.org > CNAME
        working-directory: ./docs/build
