name: Test - Documentation
on:
  # workflow_dispatch:
  pull_request:
    paths:
      - "docs/docs/**"
    branches:
      - main

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install root dependencies
        run: npm ci

      - name: Install doc dependencies
        run: npm ci
        working-directory: ./docs

      - name: Build docs
        run: npm run build
        working-directory: ./docs
